### ISSUE TITLE
On nextjs 13 _app context does not have router

### ISSUE THREAD

**Issue by Ilkhom-S** [tolgee/next-example#1]
In new version of nextjs 13. _app getInitialProps does not have router or locale information. Do we need load from getStaticProps method ?

**Comment by stepan662** [comment]
Hey, I've tested it and it works for me. Do you have your next-config properly set?
https://tolgee.io/docs/web/using_with_react/ssr/using_with_next#prepare-your-next-config

**Comment by Ilkhom-S** [comment]
Can you update to next version 13. You will see problem.

**Comment by matthiasbaldi** [comment]
First of all @stepan662  the links ends in a 404.
@Ilkhom-S how do you fixed it? Thank you.

**Comment by JanCizmar** [comment]
@matthiasbaldi There you go: https://tolgee.io/js-sdk/integrations/react/ssr/next#prepare-your-next-config

**Comment by matthiasbaldi** [comment]
Thank you. Fancy I found this page already but got some issues with NextJS 13 with import stuff etc and the compatibility over SSR and client only components.
I have to try it again, I think.
